---
- name: Converge
  hosts: all
  become: true

  vars:
    php_enable_php_fpm: true
    php_memory_limit: "192M"
    php_enablerepo: "remi-modular"

  pre_tasks:

  roles:
    - role: geerlingguy.repo-remi
    - role: geerlingguy.php

  post_tasks:
    - name: Confirm PHP configuration is correct.
      shell: php -i | grep 'memory_limit.*192'
      changed_when: false
